name: WebApp
summary: Creates a web app
description: Deploys an environment using Terraform containing a Web App
runner: devcenterdogfoodexternal.azurecr.io/public/deployment-environments/runners/terraform:latest
templatePath: web_app.tf
parameters:
  - id: "resource_name"
    name: "Resource Name"
    required: true
    type: "string"
  - id: "location"
    name: "Location"
    required: true
    type: "string"
